### PR TITLE
Fast delete a lot of old history data

### PR DESCRIPTION
**Pull request by 3xh4l3**
MySQL DELETE statement takes a long time and than need to run OPTIMIZE TABLE for free space reserved by InnoDB tables. Another faster way to delete a lot of history data is transfer needed data and drop everything else.
My english is bad, I know, but please look at the script :)

### CODE REVIEW

**Comment by burner1024** [comment]
It requires zabbix server to offline though, doesn't it?

**Comment by 3xh4l3** [comment]
Practice has shown that it is not necessary. Zabbix continues to record data on with auto increment value of the table. At the time of data transfer graphs are not shown for these data. After migration, everything is fine.

**Comment by burner1024** [comment]
OK, so if you could fix actual filename, and reference to it in readme, that would be all right, I guess

**Comment by 3xh4l3** [comment]
Thanks. I fix it.

**Comment by PeterTonoli** [comment]
Is this commit really worth the risk? There's a risk of a race condition between the ALTER TABLE and CREATE TABLE.

**Comment by 3xh4l3** [comment]
Logically, a potential risk is present. I just use it and it works. I have not tested, as Zabbix handles this exception, but I think that nothing critical will happen.

**Comment by burner1024** [comment]
So is there any real-life comparison of the two?

**Comment by PeterTonoli** [comment]
If MySQL DELETE takes a long time, why not improve the backend infrastructure? I don't see why we should allow a potentially unsafe commit, purely for performance reasons. Another question, is it the perception that the DELETE takes a long time, as the user is waiting for a command prompt? If the issue is purely perceptual, why not make the SQL transactional, with 'START TRANSACTION' / 'COMMIT'?

**Comment by burner1024** [comment]
I guess we'll have to pass on that.

**Pull request closed without merging**
